name = "pictureworks_inventory_status"
main = "worker-bundle.js"
compatibility_date = "2026-01-01"

routes = [
  { pattern = "inventory-status.wuchunkei.com", custom_domain = true },
  { pattern = "inventory-status.wuchunkei.xyz", custom_domain = true }
]

[[kv_namespaces]]
binding = "STATUS_STATE"
id = "7ee6739251d34b7aa210f0038a608d3a"
